#!/usr/bin/env node
'use strict'

const program = require('commander');

program
  .usage('<reducer_name>')
  .version(require(`${__dirname}/package.json`).version, '-v, --version')
  .parse(process.argv);

const getSrcDir = dir => {
  let srcDir = `${dir}/src`;

  dir.split('/').forEach((dirItem, index) => {
    if(dirItem === 'src')
      srcDir = dir.split('/').slice(0, index).join('/') + '/src';
  });

  return srcDir;
}

const currentDir = process.cwd();
let srcDir = getSrcDir(currentDir);
console.log(srcDir);

Promise.resolve()
  .then(() => console.log('create-actions-reducer'))
  .catch(err => {
    console.log('Fail!');
    console.error(err)
  });
