#!/usr/bin/env node
'use strict'

const program = require('commander');
const fs = require('fs-extra');

program
  .usage('<reducer_name>')
  .version(require(`${__dirname}/package.json`).version, '-v, --version')
  .parse(process.argv);

const getSrcDir = dir => {
  let srcDir = `${dir}/src`;

  dir.split('/').forEach((dirItem, index) => {
    if(dirItem === 'src')
      srcDir = dir.split('/').slice(0, index).join('/') + '/src';
  });

  return srcDir;
}

const getHeadLower = str => str.slice(0, 1).toLowerCase() + str.slice(1);
const getHeadUpper = str => str.slice(0, 1).toUpperCase() + str.slice(1);

const srcDir = getSrcDir(process.cwd());
const originDir = `${__dirname}/minimum`;

const name = program.args[0];
const xxx = getHeadLower(name);
const XXX = getHeadUpper(name);

console.log(xxx + ' ' + XXX);

Promise.resolve()
  .then(() => fs.readFile(`${originDir}/minimumActions.ts`, 'utf8'))
  .then(data => fs.outputFile(`${srcDir}/actions/xxxActions.ts`, data))
  .then(() => fs.readFile(`${originDir}/minimumReducer.ts`, 'utf8'))
  .then(data => fs.outputFile(`${srcDir}/reducers/xxxReducer.ts`, data))
  .catch(err => {
    console.log('Fail!');
    console.error(err)
  });
