#!/usr/bin/env node
'use strict'

const program = require('commander');

program
  .name('create-actions-reducer')
  .usage('<reducer_name> [options]')
  .option('-m, --minimum', 'create minimum app')
  .version(require(`${__dirname}/package.json`).version, '-v, --version')
  .parse(process.argv);

require(".")(program.args[0], program.minimum);
