#!/usr/bin/env node
'use strict'

const program = require('commander');

program
  .name('create-actions-reducer')
  .usage('<reducer_name> [options]')
  .description('create a Redux reducer & a Redux actions')
  .option('-m, --minimum', 'without sample')
  .version(require(`${__dirname}/package.json`).version, '-v, --version')
  .parse(process.argv);

require(".")(program.args[0], program.minimum);
